const MENU = {
    ABOUT : 'ABOUT',
    EXPERIENCE: 'EXPERIENCE', 
    PROJECTS: 'PROJECTS', 
    SKILLS: 'SKILLS' 
};
const PROJECTSTYPE = {
    WORK : 'Work',
    PERSONAL : 'Personal'
}
const ICONTYPE = {
    PHONE : 'PHONE',
    EMAIL: 'EMAIL',
    FILEDOWNLOAD : 'FILEDOWNLOAD',
    GITHUB: 'GITHUB',
    LINKEDIN:'LINKEDIN',
    DEMO:'DEMO',
    CODE:'CODE'
};
const DESCRIPTIONFOR = { 
    USERDESCRIPTION: 'USERDESCRIPTION'
};

export {
    MENU,
    PROJECTSTYPE,
    ICONTYPE,
    DESCRIPTIONFOR
};