const MENU = {
    ABOUT : 'ABOUT',
    EXPERIENCE: 'EXPERIENCE', 
    PROJECTS: 'PROJECTS', 
    SKILLS: 'SKILLS' 
};
const ICONTYPE = {
    PHONE : 'PHONE',
    EMAIL: 'EMAIL',
    FILEDOWNLOAD : 'FILEDOWNLOAD',
    GITHUB: 'GITHUB',
    LINKEDIN:'LINKEDIN'
};
const DESCRIPTIONFOR = { 
    USERDESCRIPTION: 'USERDESCRIPTION'
};

export {
    MENU,
    ICONTYPE,
    DESCRIPTIONFOR
};