export enum MENU {
  ABOUT = "ABOUT",
  EXPERIENCE = "EXPERIENCE",
  PROJECTS = "PROJECTS",
  SKILLS = "SKILLS"
};

export enum PROJECTSTYPE {
  WORK = "Work",
  PERSONAL = "Personal"
};

export enum ICONTYPE {
  PHONE = "PHONE",
  EMAIL = "EMAIL",
  FILEDOWNLOAD = "FILEDOWNLOAD",
  GITHUB = "GITHUB",
  LINKEDIN = "LINKEDIN",
  DEMO = "DEMO",
  CODE = "CODE",
  MAP = "MAP",
  USER = "USER"
};

export enum DESCRIPTIONFOR {
  USERDESCRIPTION = "USERDESCRIPTION"
};
